CHANGELOG.rst
src/dynamodb_encryption_sdk/__init__.py
src/dynamodb_encryption_sdk/identifiers.py

I noticed this as I was testing the pypi downloads...Python convention is to have the version in `<root namespace>.__version__`. This adds that and bumps us to `v1.0.1`.

Version convenience import

---

CHANGELOG.rst
MANIFEST.in
src/dynamodb_encryption_sdk/identifiers.py

I was certain I had updated this before release, but apparently I missed it. The `MANIFEST.in` determines what is built into the source build, and that needs to include tests and metadata.

Fix MANIFEST.in

---

test/integration/material_providers/test_aws_kms.py

fix AWS KMS integ test to correctly use Binary value rather than bytes for Python 2.7 compatibility

fix AWS KMS integ test to correctly use Binary value rather than bytes for Python 2.7 compatibility

---

CHANGELOG.rst
MANIFEST.in
src/dynamodb_encryption_sdk/identifiers.py
test/requirements.txt
test/source-build-check.sh
tox.ini

I have verified that this works locally, first creating the source build, then extracting the source build tarball and running the local test suite.
If anyone has suggestions on how to set this up as a tox environment, I'm open to ideas. If not, I'll keep thinking on that and keep moving.

Finish fixing manifest

---

test/vectors/encrypted_item/scenarios.json

The "network" flag in acceptance test scenario descriptions is intended to identify whether or not a scenario requires network access. This flag was set incorrectly for most of the scenarios.

fix "network" flag for offline acceptance test vector scenarios that were set incorrectly

---

tox.ini

In the vein of "test more permutations before committing", the thing that the `rm -f` was solving in resetdocs was the case where the generated docs directory did not already exist. I am still of the mind that we should not clobber files in the `rm` step, so this change makes the generated directory if it does not already  exist.

for tox resetdocs, make sure that the directory exists to avoid potential side effects of using rm -f

---

README.rst

The new links resolve to readthedocs. Previously, the links would follow pages
that didn't exist. This allows users to read documentation referenced in the
README by clicking on the links.
Tested by clicking on the links.

Fix lib links in README.rst

---

.travis.yml
CHANGELOG.rst
CONTRIBUTING.md
README.rst
park.cfg
setup.py
src/dynamodb_encryption_sdk/identifiers.py

*Issue #, if available:* n/a
*Description of changes:* Documentation changes to update hyperlinks, and minor version bump.

Move repository from awslabs to aws.

---

test/requirements.txt

https://github.com/spulec/moto/issues/1793
https://github.com/pyca/cryptography/issues/4415
This is a temporary fix to unblock pyca/cryptography. We need to properly fix this #85 but that problem ended up being more complex that I had anticipated due to pip's behavior of hard equalities overriding the 'ignore if present' directive. This fix will unblock the immediate issue and we can then move forward for finding the best long-term solution.

pin botocore and boto3 in tests https://github.com/spulec/moto/issues/1793

---

.travis.yml
setup.py

add CPython 3.7 CI testing and advertised support

add CPython 3.7 CI testing and advertised support

---

.travis.yml
examples/__init__.py
examples/test/examples_test_utils.py
examples/test/test_aws_kms_encrypted_examples.py
examples/test/test_most_recent_provider_encrypted_examples.py
examples/test/test_wrapped_encrypted_examples.py
setup.cfg
src/dynamodb_encryption_sdk/internal/crypto/jce_bridge/authentication.py
src/dynamodb_encryption_sdk/internal/crypto/jce_bridge/primitives.py
src/dynamodb_encryption_sdk/internal/identifiers.py
test/functional/delegated_keys/test_jce.py
test/functional/encrypted/test_client.py
test/functional/encrypted/test_resource.py
test/functional/encrypted/test_table.py
test/functional/functional_test_utils.py
test/integration/integration_test_utils.py
test/requirements.txt
test/upstream-requirements-py27.txt
test/upstream-requirements-py37.txt
tox.ini

*Issue #, if available:* #78 
We now log a warning if you create or load an HMAC key shorter than 128 bits or a RSA key shorter than 2048 bits.

add minimum key size checks and warnings

---

test/functional/hypothesis_strategies.py
test/requirements.txt

* timeout: https://hypothesis.readthedocs.io/en/master/changes.html#v3-16-0
* max_iterations: https://hypothesis.readthedocs.io/en/master/changes.html#v3-56-0

remove use of deprecated hypothesis features

---

CHANGELOG.rst
src/dynamodb_encryption_sdk/encrypted/item.py
src/dynamodb_encryption_sdk/internal/utils.py
src/dynamodb_encryption_sdk/material_providers/most_recent.py
src/dynamodb_encryption_sdk/material_providers/store/meta.py
test/functional/functional_test_utils.py
test/functional/material_providers/test_most_recent.py
test/functional/test_structures.py
test/integration/integration_test_utils.py
test/integration/material_providers/store/test_meta.py
test/integration/material_providers/test_most_recent.py

After #102 failed to fix the bug that the customer was seeing in cache use, digging into this deeper I found that the `encrypt_ddb_item` function was calling `.refresh()` on the crypto materials provider every pass. That component was not supposed to ever use that interface.
Also included here is additional logging since we didn't have much of any in either `MetaStore` or `MostRecentProvider`.

Actually fix MostRecentProvider reuse bug

---

src/dynamodb_encryption_sdk/internal/utils.py
test/functional/encrypted/test_client.py
test/functional/encrypted/test_resource.py
test/functional/encrypted/test_table.py
test/functional/functional_test_utils.py
test/functional/internal/test_utils.py

Addresses #92, #91 
Changes the encrypt_batch_write_item utility method to check for UnprocessedItems in the response, and replace them with the original plaintext items.
Couple talking points:
- The encryption process is currently overwriting the plaintext item value, and in order to enable reverting it back I needed to deep copy the RequestItems.
- Handling the possible lack of schema information when searching out the correct plaintext item meant having a fallback that requires all the attributes not marked for encryption to match; a brute-force way of making sure the key attributes match since they aren't encrypted. Not sure if there's a more elegant way.
- I may have put my tests in the wrong place :)
- My tests are low-level implementation tests, should there be a higher-level test …

Handle unprocessed items in batch write responses

---

src/dynamodb_encryption_sdk/material_providers/aws_kms.py
src/dynamodb_encryption_sdk/structures.py

An update in `pylint` started actually checking for these. It looks like when `black` reformatted some multi-line definitions at some point, it collapsed all of the per-line Python 2 typehints into a single line that no longer correctly defines the interface.
Also, a couple set definitions that `pylint` suggested simplifying.

fix Python 2 typehints that black mangled

---

CHANGELOG.rst
src/dynamodb_encryption_sdk/encrypted/client.py
src/dynamodb_encryption_sdk/internal/utils.py
test/functional/encrypted/test_client.py
test/functional/encrypted/test_item.py
test/functional/functional_test_utils.py
test/integration/encrypted/test_client.py
test/integration/encrypted/test_resource.py
test/integration/encrypted/test_table.py
test/integration/integration_test_utils.py
test/integration/material_providers/test_aws_kms.py

#118 
* Added integration tests that test the scan paginator with KMS crypto materials providers.
* Single-sourced logic for decrypting a list of items, and updated both `EncryptedPaginator` and `decrypt_multi_get` to use it.

Fix EncryptedPaginator to successfully decrypt

---

test/integration/encrypted/test_client.py
test/integration/encrypted/test_resource.py
test/integration/encrypted/test_table.py
test/integration/integration_test_utils.py
test/integration/material_providers/test_aws_kms.py
tox.ini

*Issue #, if available:* #122 https://github.com/pyca/cryptography/issues/4979
* Fixes upstream test environments to correctly block all environment variables.
* Fixes integration test parameterization logic to fail at execution time rather than test collection time.

Fix upstream tests

---

CHANGELOG.rst
src/dynamodb_encryption_sdk/material_providers/aws_kms.py
test/unit/material_providers/test_aws_kms.py
test/unit/unit_test_utils.py

*Issue #, if available:* #124 
`AwsKmsCryptographicMaterialsProvider` was incorrectly squashing any custom regional clients provided in the constructor.
Also included here are tests to make sure that *no* values provided in the constructor are squashed.

Regional clients

---

CHANGELOG.rst
examples/src/aws_kms_encrypted_item.py
examples/src/aws_kms_encrypted_resource.py
examples/src/aws_kms_encrypted_table.py
examples/src/most_recent_provider_encrypted_table.py
examples/src/wrapped_rsa_encrypted_table.py
examples/src/wrapped_symmetric_encrypted_table.py
src/dynamodb_encryption_sdk/structures.py
test/unit/test_structures.py

*Issue #, if available:* #127 
Fixes #127 by removing "attributes" from `EncryptionContext` str/repr values.

Remove "attributes" from EncryptionContext str/repr

---

tox.ini

*Issue #, if available:* n/a
*Description of changes:* CI is failing for docs because `mypy-py2` requires Python 2, but `basepython` was set to Python 3.

chore: Fix basepython for mypy-py2.

---

buildspec.yml
codebuild/python2.7.yml
codebuild/python3.5.yml
codebuild/python3.6.yml
codebuild/python3.7.yml
codebuild/python3.8.yml
tox.ini

Adding buildspec to batch build
multiple Python runtimes
* Python 2.7
* Python 3.5
* Python 3.6
* Python 3.7
* Python 3.8

chore: Add AWS CodeBuild buildspec

---

CHANGELOG.rst
src/dynamodb_encryption_sdk/identifiers.py
src/dynamodb_encryption_sdk/material_providers/most_recent.py
test/functional/material_providers/test_most_recent.py

BREAKING CHANGE: Removes the MostRecentProvider, which is replaced by the CachingMostRecentProvider.

fix!: Remove the MostRecentProvider.

---

examples/src/aws_kms_encrypted_client.py
examples/src/aws_kms_encrypted_resource.py

*Issue #, if available:* 
*Description of changes:* Fixes pylint report for R1729(use-a-generator). See: https://github.com/PyCQA/pylint/pull/3309

chore: Fix pylint R1729(use-a-generator)

---

buildspec.yml
codebuild/coverage/coverage.yml
setup.cfg
tox.ini

Remove code coverage from base python command, add a dedicated code coverage environment, as well as code build specs to run it.
See also: https://github.com/aws/aws-encryption-sdk-python/pull/325
Threshold of 90% chosen because current coverage is 91%.
*Testing:*
Building gives me:
```
Required test coverage of 90.0% reached. Total coverage: 91.05%
```
If I bump the threshold to 95, the build fails with:
```
FAIL Required test coverage of 95.0% not reached. Total coverage: 91.05%
```

chore: Fail build if code coverage is too low

---

test/README.rst
test/upstream-requirements-py27.txt
test/upstream-requirements-py37.txt

Dependabot's attempt failed because 4.1 is in a bad state on pypi: https://github.com/aws/aws-dynamodb-encryption-python/pull/154

Manually updating rsa version in upstream requirements

---

.github/workflows/ci_tests.yaml
buildspec.yml
codebuild/python3.9.yml
setup.py
tox.ini

We already had some 3.8 testing, this adds 3.9 and adds both to our list of supported versions.

Add explicit support for py38 and py39

---

src/dynamodb_encryption_sdk/material_providers/most_recent.py

*Description of changes:* Disabling pylint "consider-using-with" on those two lines to make the static analysis happy again. The locking logic in those sections is deliberate, and refactoring to using 'with' is not worth the risk of updating any of this logic.

chore: Fix static analysis

---

README.rst
SUPPORT_POLICY.rst
doc/conf.py
setup.py
src/dynamodb_encryption_sdk/delegated_keys/__init__.py
src/dynamodb_encryption_sdk/materials/__init__.py

chore: Add support policy

---

codebuild/release/validate.yml

We didn't update the release specs when we added the new MRK examples, so they're not yet passing through the expected MRK key ids.
Expected variables are here: https://github.com/aws/aws-dynamodb-encryption-python/blob/master/test/integration/integration_test_utils.py#L30-L31

chore: Add MRK key ids to codebuild specs

---

examples/src/pylintrc
examples/test/pylintrc
src/pylintrc
test/pylintrc

*Issue #, if available:* Ignore this pylint recommendation while we still support Python 3.5

chore: Fix CI

---

.github/workflows/ci_static-analysis.yaml
.github/workflows/ci_tests.yaml
codebuild/python3.5.yml
codebuild/python3.6.yml
codebuild/python3.7.yml
codebuild/python3.8.yml
codebuild/python3.9.yml
examples/test/examples_test_utils.py
examples/test/test_aws_kms_encrypted_examples.py
src/dynamodb_encryption_sdk/material_providers/most_recent.py

*Issue #, if available:* Update Minor Python versions used for testing.
- In CodeBuild, use the latest release of Python Minor versions as of 2021-11-08
- In GitHub, use the latest version of `actions/setup-python`
- Address linting issues

ci: Update CI

---

src/dynamodb_encryption_sdk/__init__.py
src/dynamodb_encryption_sdk/compatability.py
test/pylintrc
test/unit/test_compatability.py

*Issue #, if available:* Check Python Runtime
*Description of changes:* Implements A runtime check on the Python Version.
Runtime Check:
- Issues a WARNING if the Python Version will become/is unsupported.
- Will start issuing WARNING for Python Version less than 3.6.

feat(compatability): Check Python Runtime

---

buildspec.yml
codebuild/python3.10.yml
tox.ini

- Add Python 3.10 to tox
- Add Python 3.10 testing to CodeBuild

ci(py310): test against Python 3.10.0

---

.readthedocs.yaml
doc/requirements.txt

Same fixes as here: https://github.com/aws/aws-encryption-sdk-python/commit/193dfc70c44b80e28c9f5abe2000db6084f83ccf
Except this repo didn't yet have a dedicated readthedocs config, so I've added it.
See failing build here: https://readthedocs.org/projects/aws-dynamodb-encryption-python/builds/15239121/

chore: Fix readthedocs builds

---

codebuild/release/validate.yml
doc/conf.py
doc/requirements.txt
examples/tox.ini

Fixes discovered during the most recent release.
Also fix the doc generation. When we pulled in the newest version of sphinx it changed how the configuration works, specifically the `autodoc_default_flags` parameter we were using is now deprecated. See [docs](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_flags)
To see the effect, compare the good [stable docs](https://aws-dynamodb-encryption-python.readthedocs.io/en/stable/lib/materials_providers/aws_kms.html) to the empty [latest docs](https://aws-dynamodb-encryption-python.readthedocs.io/en/latest/lib/materials_providers/aws_kms.html)
*Testing:*
CI is failing the broken link check on the docs because it always hits the public docs (which don't yet incorporate this …

chore: Fix release validation

---

.github/workflows/ci_tests.yaml
codebuild/python2.7.yml
codebuild/python3.6.yml
codebuild/python3.8.yml
dev_requirements/linter-requirements.txt
doc/conf.py
examples/test/pylintrc
src/pylintrc
test/pylintrc
test/requirements.txt
test/unit/material_providers/test_aws_kms.py
tox.ini

Pins linter dependencies in `master-2.x` branch
~Most notably for py2 tests instead of using the requirements file in `test/` it uses the pinned dependencies in `test/upstream-requirements-py27.txt`.~

chore: pin linter dependencies

---

dev_requirements/linter-requirements.txt

chore(deps): bump black from 22.1.0 to 22.3.0

---

codebuild/coverage/coverage.yml
codebuild/python3.10.yml
codebuild/python3.7.yml
codebuild/python3.8.yml
codebuild/python3.9.yml
codebuild/release/prod-release.yml
codebuild/release/test-release.yml
codebuild/release/validate.yml

This PR is to pin tox dependency < 4.0 since latest one cause formatting issues.

fix: pin tox dependency < 4.0

---

src/dynamodb_encryption_sdk/encrypted/client.py
src/dynamodb_encryption_sdk/encrypted/resource.py
src/dynamodb_encryption_sdk/encrypted/table.py

*Issue #, if available:* Broken links in our docs.
`fix(docs): update broken links`

fix(docs): update broken links

---

dev_requirements/test-requirements.txt
test/unit/material_providers/test_aws_kms.py
test/upstream-requirements-py311.txt
test/upstream-requirements-py37.txt
tox.ini

We ([pyca/cryptography](https://github.com/pyca/cryptography)) run this project's test suite in our own CI  as part of our downstream testing. However, I noticed recently that while this project installs xdist, it doesn't use it. This PR fixes one small issue which caused xdist to fail and enables it across your test suite. This should allow us to drop our test times roughly in half for `cryptography`. Enjoy!
(Apologies for a few small extraneous whitespace fixes, my editor automatically does that)

fix parallel test support and enable in CI

---

CHANGELOG.rst
README.rst
examples/README.rst

*Issue #, if available:* As part of the new Database Encryption release, the docs for DDBEC-Python have moved. 

fix(docs): Update AWS Doc URLs

---

CONTRIBUTING.md
README.rst
src/dynamodb_encryption_sdk/internal/utils.py
src/dynamodb_encryption_sdk/structures.py
tox.ini

chore: address doc linter findings

---

.github/workflows/ci_tests.yaml
buildspec.yml
codebuild/python3.10.yml
codebuild/python3.11.yml
codebuild/python3.12.yml
codebuild/python3.7.yml
codebuild/python3.9.yml
dev_requirements/ci-requirements.txt
tox.ini

feat: test Python 3.12

---

codebuild/python3.12.yml

- codebuild ci is failing with `pyenv 3.12.0 already exists`, with this change ci will skip `pyenv` installation if already exists

chore(ci): skip pyenv installation if already exists

---

.github/workflows/ci_tests.yaml
.readthedocs.yaml

fix(docs; gha): updated .readthedocs.yaml; macos-latest to macos-12

---

test/unit/test_compatability.py
test/upstream-requirements-py311.txt

chore(deps): Update pytest version in upstream-requirements-py311.txt

---

CHANGELOG.rst
SUPPORT_POLICY.rst
src/dynamodb_encryption_sdk/identifiers.py

- Added 37 deprecation to changelog
- Updated version in identifiers.py file

chore(CHANGELOG): 3.3.0

---

codebuild/release/prod-release.yml
codebuild/release/test-release.yml

Updated the TestPyPiCryptoTools and PyPiCryptoTools username password to API Token username and password in the codebuild release scripts

chore(release): Updated API Token username password for Test PyPI and PyPI
